#!/bin/bash

curr_year=$(date -j +%Y)
year=${1-$curr_year}

mkdir -p $year/00
latest=$(ls -d $year/* | sort -t '-' -k2,2n | tail -n 1)
rm -r $year/00

if [[ $latest =~ $year/([0-9]{2}) ]]; then
  current=${BASH_REMATCH[1]}
  next=$((10#$current + 1))

  if ((next > 25)); then
    echo "All days for year $year already created"
    exit 0
  fi

  if ((next < 10)); then
    day="$year/0$next"
  else
    day="$year/$next"
  fi
else
  day="$year/01"
fi

mkdir -p "$day"
touch "./$day/example.txt"
touch "./$day/input.txt"

cat ./template.go > "./$day/solution.go"
