#!/bin/bash

latest=$(ls -d 2024-* | sort -t '-' -k2,2n | tail -n 1)
curr_year=$(date -j +%Y)
year=${1-$curr_year}

if [[ $latest =~ $year-([0-9]{2}) ]]; then
  current=${BASH_REMATCH[1]}
  next=$((10#$current + 1))

  if ((next > 25)); then
    echo "All days for year $year already created"
    exit 0
  fi

  if ((next < 10)); then
    day="$year-0$next"
  else
    day="$year-$next"
  fi
else
  day="$year-01"
fi

mkdir "$day"
touch "./$day/example.txt"
touch "./$day/input.txt"

sed "s/\\\$DAY/$day/g" ./template.go > "./$day/solution.go"
