#!/bin/bash
curr_year=$(date -j +%Y)
year=${1-$curr_year}

latest=$(cd $year && ls -d * | sort -t '-' -k2,2n | tail -n 1)
day=${2-$latest}
watch_dir="$year/$day"
last_modified=0

while true; do
    a=$(find "$watch_dir" -type f -exec stat -f "%m" {} + | sort -nr | head -n1)
    b=$(find "utils" -type f -exec stat -f "%m" {} + | sort -nr | head -n1)
    new_modified=$(($a + $b))

    if [ "$new_modified" -ne "$last_modified" ]; then
        clear
        echo "$watch_dir:"
        echo "---"
        last_modified=$new_modified
        go run "$watch_dir/solution.go"
    fi

    sleep 0.3
done
