#!/bin/bash

watch_dir="$1"
last_modified=0

while true; do
    new_modified=$(find "$watch_dir" -type f -exec stat -f "%m" {} + | sort -nr | head -n1)

    if [ "$new_modified" -ne "$last_modified" ]; then
        clear
        last_modified=$new_modified
        go run "$watch_dir/solution.go"
    fi

    sleep 0.3
done
