#!/bin/bash
curr_year=$(date -j +%Y)
year=${1-$curr_year}

latest=$(ls -d $year/* | sort -t '-' -k2,2n | tail -n 1)
watch_dir=${1-$latest}
last_modified=0

while true; do
    new_modified=$(find "$watch_dir" -type f -exec stat -f "%m" {} + | sort -nr | head -n1)

    if [ "$new_modified" -ne "$last_modified" ]; then
        clear
        echo "$watch_dir:"
        echo "---"
        last_modified=$new_modified
        go run "$watch_dir/solution.go"
    fi

    sleep 0.3
done
